version: '3.4'

services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: medical-platform
    networks:
      default:
        aliases:
          - db

  web:
    build:
      context: ./bernerslee
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      default:
        aliases:
          - bernerslee

  ai:
    build:
      context: ./mccarthy
    networks:
      default:
        aliases:
          - mccarthy
